import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Backend Engineering
  backendV1: [{type: 'autogenerated', dirName: 'Backend Engineering/Version 1'}],
  backendV2: [{type: 'autogenerated', dirName: 'Backend Engineering/Version 2'}],
  backendV3: [{type: 'autogenerated', dirName: 'Backend Engineering/Version 3'}],

  // Computer Network
  networkV1: [{type: 'autogenerated', dirName: 'Computer Network/Version 1'}],
  networkV2: [{type: 'autogenerated', dirName: 'Computer Network/Version 2'}],

  // DBMS
  dbmsV1: [{type: 'autogenerated', dirName: 'DBMS/Version 1'}],
  dbmsV2: [{type: 'autogenerated', dirName: 'DBMS/Version 2'}],

  // DevOps
  devopsV1: [{type: 'autogenerated', dirName: 'DevOps/Version 1'}],
  devopsV2: [{type: 'autogenerated', dirName: 'DevOps/Version 2'}],

  // Operating System
  osV1: [{type: 'autogenerated', dirName: 'Operating System/Version 1'}],
  osV2: [{type: 'autogenerated', dirName: 'Operating System/Version 2'}],

  // System Design
  systemDesignV1: [{type: 'autogenerated', dirName: 'System Design/Version 1'}],
  systemDesignV2: [{type: 'autogenerated', dirName: 'System Design/Version 2'}],
};

export default sidebars;
